### ISSUE TITLE
add a resources post

### ISSUE THREAD

**Issue by kriemo** [rnabioco/bmsc-7810-pbda#5]
with links to other tutorials, ebooks, etc. to provide additional explanations and exercises.

**Comment by kwells4** [comment]
good tidyverse examples and exercises: https://rpubs.com/cliex159/864632

**Comment by kriemo** [comment]
closed by [7dee6e6](https://github.com/rnabioco/bmsc-7810-pbda/commit/7dee6e61cb6d226b98434ab84859c5a8df1d7571)
